global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'luisbank_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ledger_api:8000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
