apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-sa
  namespace: ledger

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ledger-role
  namespace: ledger
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ledger-rolebinding
  namespace: ledger
subjects:
  - kind: ServiceAccount
    name: ledger-sa
    namespace: ledger
roleRef:
  kind: Role
  name: ledger-role
  apiGroup: rbac.authorization.k8s.io
