apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-redis
  namespace: ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-redis
  template:
    metadata:
      labels:
        app: ledger-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-redis
  namespace: ledger
spec:
  selector:
    app: ledger-redis
  ports:
    - port: 6379
      targetPort: 6379
